//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlcoolGasolina {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlcoolGasolina.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol.
        /// </summary>
        internal static string AlcoolText {
            get {
                return ResourceManager.GetString("AlcoolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string BotaoCalcular {
            get {
                return ResourceManager.GetString("BotaoCalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate costs.
        /// </summary>
        internal static string CalcularTitle {
            get {
                return ResourceManager.GetString("CalcularTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Fuel.
        /// </summary>
        internal static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoline.
        /// </summary>
        internal static string GasolinaText {
            get {
                return ResourceManager.GetString("GasolinaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Gas Station.
        /// </summary>
        internal static string GasStation {
            get {
                return ResourceManager.GetString("GasStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the nearest.
        /// </summary>
        internal static string GasStationGoButton {
            get {
                return ResourceManager.GetString("GasStationGoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Gas Station.
        /// </summary>
        internal static string GasStationMapLoad {
            get {
                return ResourceManager.GetString("GasStationMapLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string HistoricDateText {
            get {
                return ResourceManager.GetString("HistoricDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string HistoricFuelText {
            get {
                return ResourceManager.GetString("HistoricFuelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        internal static string HistoricLitersText {
            get {
                return ResourceManager.GetString("HistoricLitersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (L).
        /// </summary>
        internal static string HistoricValueText {
            get {
                return ResourceManager.GetString("HistoricValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic.
        /// </summary>
        internal static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol Price.
        /// </summary>
        internal static string PrecoAlcoolText {
            get {
                return ResourceManager.GetString("PrecoAlcoolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Price.
        /// </summary>
        internal static string PrecoGasolinaText {
            get {
                return ResourceManager.GetString("PrecoGasolinaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SalvarText {
            get {
                return ResourceManager.GetString("SalvarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Average Is.
        /// </summary>
        internal static string TextoValorMediaCalcular {
            get {
                return ResourceManager.GetString("TextoValorMediaCalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of fuel.
        /// </summary>
        internal static string TipoCombustivelText {
            get {
                return ResourceManager.GetString("TipoCombustivelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol x Gasoline.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value suplied.
        /// </summary>
        internal static string ValorAbastecidoText {
            get {
                return ResourceManager.GetString("ValorAbastecidoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter value.
        /// </summary>
        internal static string ValorLitroText {
            get {
                return ResourceManager.GetString("ValorLitroText", resourceCulture);
            }
        }
    }
}
